feat: extended laravel 6.X to 9.0 upgrade changes (#32980)
* fix: use quotes in keys

* uncommented finally block

* Change in Redis Circuit Breaker Test and test Icici(#33609)

* Changed Encrypt Function

* test case

* Changed original data

* Changed length of secret column in keys table to 256.

* Revert "test case"

This reverts commit 6f77a3a7cc0a216c4ef5874579cf36297bd102db.

* test case

Co-authored-by: vasanthikakarla <kakarla.vasanthi@razorpay.com>

* config change for public key (#33620)

* onggi image changed for docker web

* Change for testSoftLimitEscalation1 (#33625)

* Changed Encrypt Function

* test case

* Changed original data

* Changed length of secret column in keys table to 256.

* Revert "test case"

This reverts commit 6f77a3a7cc0a216c4ef5874579cf36297bd102db.

* test case

* Commit for testSoftLimitEscalation1

Co-authored-by: vasanthikakarla <kakarla.vasanthi@razorpay.com>

* onggi image changed

* is_array check added

* UT fixed

* replaced getClientSize by getSize

* fix: factory create call

* fix: testImplicitVariableWithSubmerchantPartnerESPricingRules

* fixed breaking test cases for transaction limit (#33547)

* fix failing tests (#33649)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* fix: testCreatePartnerSubmerchantWithValidContactMobileForX

* builder fixes (#33650)

* Card test php upgrade test fix (#33655)

* card test fix

* fix

* fix

* edge partner issue

* Update app/Http/BasicAuth/BasicAuth.php

Co-authored-by: Rishabh Gupta <rishabh.gupta@razorpay.com>

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>
Co-authored-by: Rishabh Gupta <rishabh.gupta@razorpay.com>

* fixed test cases (#33657)

* update phpunit

* updated error reporting

* add logs

* apk add wkhtmltopdf

* oauth common issue fixes (#33666)

oauth common fixes

* finally block removed

* changes

* fix Care test cases (#33660)

* fix test case

* testReceiveFreshdeskWebhookOnTicketReplyFirstResponseTimeDataExist fixed

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* test

* test

* fix: use factory() static method

* fix: pass accessToken string

* remove binary path

* test

* test

* test

* fix: args in UploadedFile constr

* Fixed oauth test cases (#33648)

* fixed oauth test cases

* fixed DeleteWorkflowAction test case

* fixed 2fa token issue

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* terminal auth selection exception (#33668)

* terminal auth selection exception

* null check handling

* syntax error fix

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* fix netbanking gateway tests

* Fix for testVisaFraudReportBatchCreated (#33680)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* testRecurringMandateCreateOnDark fix (#33670)

* test fix

* test case fix

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* Laravel 9 upgrade extended payout fixes (#33682)

* Fix PayoutSourceTest.php

* Fix test cases

* Fix test cases

* Comment redis mock

* Fix test cases

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* added bug fix (#33645)

* test

* fix: testCreateSubMerchantWithMobileNoByAggregatorBatchForX

* fix: 2 test cases on es client

* fix: edge-passport in composer

* fix: 2 test cases on es client

* test

* test

* test

* Fix Tests testGetHostedPageForKeylessHeaderEnabledMerchant (#33696)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* test

* test

* test

* test

* namespace casing corrected (#33693)

namespace casing corrected

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* Batch test case failure fix (#33701)

* Changed the way we are passing verify certs

* Changed the way we are passing verify certs

* Final update

* feat: rename Nbplus folder to NbPlus to fix gateway-2 test cases

* test

* fix: testEmandateRegistrationForLateAuth

* fix testWeakPassword test case (#33699)

* Laravel 9 upgrade extended payout fixes (#33690)

* Fix PayoutSourceTest.php

* Fix test cases

* Fix test cases

* Comment redis mock

* Fix test cases

* Fix test case

* Fix test case

* Fix test case

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* fix test cases testBearerAuthWithTamperedToken (#33710)

* fix test cases

* comment fix

* [NOCODE] EOL upgrade test case failures fix (#33705)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* added import (#33694)

* Fix for Shield Tests (#33691)

* Added Logs

* Test2

* Update FraudDetectionTest.php

* Made changes

* Made changes

* Made change

* Removed Comparison In string

* Removed Unrequired Changes

* Recurring test case fix (#33662)

* test

* test fix

* Revert "test fix"

This reverts commit 0c8e7fa1c12123af8e9088f71f394249fac07d39.

* test: phpunit changes

* Fixed the NPS test (#33719)

* fix test cases OauthMigrationToken.php (#33706)

* fix test cases

* nit

* fix

* comment fixes

* comment fixes

* [NOCODE] Fixed risky test cases and  get reciept test case failures (#33721)

* [NOCODE] fixed risky test cases

* [NOCODE] fixed get reciept test case failures

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* removed necessity for type coersion (#33725)

* fixing core redis test (#33735)

* fixing core redis test

* imports

* fix (#33720)

Co-authored-by: apatra9 <a.patra56789@gmail.com>
Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* fix for mutex issue in refund test

* Laravel 9 upgrade extended payout fixes (#33740)

* Fix PayoutSourceTest.php

* Fix test cases

* Fix test cases

* Comment redis mock

* Fix test cases

* Fix test case

* Fix test case

* Fix test case

* Fix test case

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* Fix testAddCustomPayoutPurposeOfNumericType test case (#33767)

* Fix PayoutSourceTest.php

* Fix test cases

* Fix test cases

* Comment redis mock

* Fix test cases

* Fix test case

* Fix test case

* Fix test case

* Fix test case

* Bump l4-settings version to 1.2.0

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* Disabled Encoding For Axis (#33678)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* skipped unused verify test cases

* fix es mock issue

* Mutex Mockery change (#33757)

* Mutex Mockery change

* redis fix

* Tested Locally

* Included Circuit Breaker in the phpunit.

Co-authored-by: vasanthikakarla <kakarla.vasanthi@razorpay.com>
Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* added yesbank terminal

* fix added for UploadFile

* Card laravel 9 upgrade extended (#33808)

* fiux

* fixed

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* skipped the mpesa recon test cases

* feature 4 suite reverted

* fix for es mock in feature 4 suite

* debit UT fixed related to FDesk

* Laravel 9 upgrade extended gateway suite (#33814)

* [Gatweway suite] add pgp-encrypted mime type

* minor fix

* test case fix (#33817)

* renamed the folder

* renamed the netbanking bob namespace

* skipped couple of test case

* Fix Payout Tests - PHP EOL (#33830)

* [UPI][Mindgate] fix testcase for PHP Upgrade (#33728)

* Fix Payout Tests - PHP EOL (#33832)

* removed the pretty printer

* updated php unit file

* fixed failures for feature-4 test suite

* fix for feature 2 test failure

* error reporting changed

* modified error reporting

* reverted BaseProxyControllerTest changes

* reverted error reporting changes

* middleware added

* fix added for feature 6 failure

* fix added for feature 6 failure

* Magic cx/laravel upgrade fix cod (#33868)

* null check

* run only 1 test

* Revert "run only 1 test"

This reverts commit 741123e969b08383693d0f55f755f9b4d737b0fc.

* reverted public coll change

* refactored file names (#33882)

* skipped commission invoice generate

* resolved master conflict

* resolved master conflict

* Fix Preferences UT's Failing With TypeError On PHP Upgrade Branch (#33900)

* Fix Preferences UT's Failing With TypeError On PHP Upgrade Branch

__PROBLEM:__

`testGetCheckoutRouteWithDeviceToken()` & `testGetCheckoutRouteWithAndroidMetadataNoSession`
are failing with error:

```
TypeError: get_class(): Argument #1 ($object) must be of type object, array given
```

__CAUSE:__

Behaviour of `get_class()` has changed in PHP 8.0.0. If get_class() is called
with anything other than an object, TypeError is raised. Prior to PHP 8.0.0,
an E_WARNING level error was raised.

__FIX:__

1. Do not call `toArrayPublic()` on `$tokens` and le it remain as PublicCollection
for further processing.
2. Add an `is_object()` check before calling `get_class` in `isPublicCollection()`

* Call toArrayPublic() on $tokens in validateDeviceTokens()

validateDeviceTokens() is also called from Controller & is breaking tests due to
invalid output format of tokens.

* Add Missing AND Condition in IF Clause

* Accept Array in removeNonCompliantCardTokens()

__PROBLEM:__

`testGetCheckoutRouteWithDeviceToken`, `testGetCheckoutRouteWithAndroidMetadataNoSession`

are failing with the following error

```
TypeError: RZP\Models\Customer\Token\Core::removeNonCompliantCardTokens():
Argument #1 ($tokens) must be of type RZP\Models\Base\PublicCollection, array given,
called in /__w/api/api/app/Models/Merchant/Checkout.php on line 1002
```

* removed the unused key files

* updated slack laravel

* fix Headers::removeAll, Headers::getAll in Mailable (#33986)

* add netbanking_pnb to spout gateways (#34052)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* change the docker file for curl downgrade

* fix: guzzle adaptor class name (#34149)

* changes for devstack header (#34155)

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>

* Set dev-serve context header only when available (#34167)

* hotfix by reverting ledger merchant onboarding code changes

* changes from master

* fix: optional param before req param

* remove unused import

* fixed ut failures

* added if check

* error handler changed

* fix: mockery args matching conflict (#34298)

* mask contact details bugfix (#34214)

* fixed app key_exits error

* hotfix

* fix: testAddPartnerAddedFeaturesToSubmerchantOnMode

* add empty for basicauth when calling getpassportjwt method

* feat: increase memory to 8 GB in phpunit

* updated readme

* added mailgun upgrade changes (#34372)

* [UPI][ICICI] fix testcase for PHP Upgrade (#34026)

* [UPI][ICICI] fix testcase for PHP Upgrade

* throw exception in decrypt

* fixed utility'

* Fix Authz Admin Client (#34384)

* branch to deploy

* Revert "Add experiment for partner activation workflow bugfix (#34358)"

This reverts commit 31c96412e60fb42e8be2245b6592e8cb234ee77d.

* Revert "PRTS 2081 (#34116)"

This reverts commit 3b33a8565bf53b2f048e16a92f13998d1822b7ec.

* trigger build

* Fix razorx flag for saved card payment and nil check for input (#34366)

(cherry picked from commit 1ce01d00582eda681eec9ccac0fbf7df4148f324)

* Revert "Fix razorx flag for saved card payment and nil check for input (#34366)"

This reverts commit 63a2eb616af02aaf1a686aada2123ff2cfbe13a2.

* remove log parameter (#34411)

* remove log parameter (#34413)

* Fix Authz Swagger Client

* readme changes

* updated the base image

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>
Co-authored-by: Jayesh Kumar <jayesh.kumar@razorpay.com>
Co-authored-by: Laksh sadhwani <47391874+Laaaaksh@users.noreply.github.com>
Co-authored-by: vasanthikakarla <kakarla.vasanthi@razorpay.com>
Co-authored-by: Akash Patel <akashkumar.patel@razorpay.com>
Co-authored-by: rajashreekhandelia <rajashree.khandelia@razorpay.com>
Co-authored-by: ankit <30381705+ankitpal11@users.noreply.github.com>
Co-authored-by: Rishabh Gupta <rishabh.gupta@razorpay.com>
Co-authored-by: samhit-bhogavalli <87688921+samhit-bhogavalli@users.noreply.github.com>
Co-authored-by: Shashi <shashi.sah@razorpay.com>
Co-authored-by: asthemus <ashray.sinha28@gmail.com>
Co-authored-by: Akhilesh-Sirohi <akhileshsirohii@gmail.com>
Co-authored-by: Sarthak Shekhawat <sarthak.shekhawat@razorpay.com>
Co-authored-by: Mohamed Safwan <97943367+m-safwan@users.noreply.github.com>
Co-authored-by: robo <surya.kanna@razorpay.com>
Co-authored-by: Vivek S <vivek.s@razorpay.com>
Co-authored-by: Harshal Charadva <92292747+harshal-charadva@users.noreply.github.com>
Co-authored-by: Enigma <52568191+k-shrestha@users.noreply.github.com>
Co-authored-by: Sanjib Devnath <85101790+razorpay-sanjib@users.noreply.github.com>
Co-authored-by: tushar-dubey-rzr <71688510+tushar-dubey-rzr@users.noreply.github.com>
Co-authored-by: Saketh Vallakatla <saketh21v@gmail.com>
Co-authored-by: ArjunTomer <arjun.tomer@razorpay.com>
Co-authored-by: Arunabha Patra <47187868+apatra9@users.noreply.github.com>
Co-authored-by: apatra9 <a.patra56789@gmail.com>
Co-authored-by: Rajan Sharma <56467449+Rajan-226@users.noreply.github.com>
Co-authored-by: Anish Rajan <anish.rajan@razorpay.com>
Co-authored-by: Vikas Naidu <vck173@gmail.com>
Co-authored-by: Nawed Diwan <99803244+nawedr@users.noreply.github.com>
Co-authored-by: ShireenMeher <66132759+ShireenMeher@users.noreply.github.com>
Co-authored-by: Rishi Ramawat <rishi-ramawat@users.noreply.github.com>
Co-authored-by: harijvs <srihari.j@razorpay.com>
Co-authored-by: JaswanthKarumuri <98880795+JaswanthKarumuri@users.noreply.github.com>
Co-authored-by: Sujan Adiga <16635045+sujanadiga@users.noreply.github.com>
Co-authored-by: Abhay Kumar <abhaya.kumar@razorpay.com>
Co-authored-by: udayraj-rzp <103119590+udayraj-rzp@users.noreply.github.com>
Co-authored-by: vasanthikakarla <84132254+vasanthikakarla@users.noreply.github.com>
Co-authored-by: Pranithkampelly <pranithkampelly@gmail.com>
Co-authored-by: hemanth132 <hemanth.muppuri@razorpay.com>
Co-authored-by: Manas-Bagai <87698149+Manas-Bagai@users.noreply.github.com>
Co-authored-by: Bhavya Y <bhavya.y@razorpay.com>
Co-authored-by: Tanish Gupta <tanish.gupta@razorpay.com>
Co-authored-by: ChiragChiranjib <58375906+ChiragChiranjib@users.noreply.github.com>