CE-5260: Fix SQL Syntax Error Caused by Semicolon in Presto Query (#29133)
__Problem:__

The RTB cron failed to run on 27th March 2022 with the following error:

```
SYNTAX_ERROR: line 11:14: mismatched input ';'. Expecting: '%', '*', '+', ',',
'-', '.', '/', 'AND', 'AT', 'EXCEPT', 'FETCH', 'HAVING', 'INTERSECT', 'LIMIT',
'OFFSET', 'OR', 'ORDER', 'UNION', 'WINDOW', '[', '||', <EOF>, <predicate>
```

__Cause:__

Not sure why but presto didn't like the semicolon in the query. The query works
fine when run on Querybook ¯\_(ツ)_/¯

__Fix:__

I have removed the semicolon & have added a limit clause instead