feat: new federated module (digital-bills) to pg dashboard [BILLMETECH-93] (#14187)
* feat: setup monorepo base

* fix: add yarn - no hoist

* fix: resolve yarn nohoist issue

* refactor: npm scripts to use yarn cli

* fix: node version

* refactor: npm scripts to use yarn cli

* fix: yarn hoisting issue

* fix: workflow script

* fix: workflow script

* feat: upgrade to react-router v5

* feat: upgrade react-router-dom v5 to v6 (#13141)

* chore: install react-router-dom@6
* chore: change component prop to element
* feat: removed search usage from ModalDialog (#13157)
* chore: add local deprecated withRouter and RouteComponentProps
* chore: refactor withRouter imports to point to local version
* chore: replace Switch with Routes
* feat: migrate Redirect to Navigate
* feat: migrate Navlink props & HandleIndex
* feat: showWhenRoute issue fixes (#13209)
* feat: refactored all Route
* feat: RouteGuard added
* added index to navigated route
* chore: changed defaultPath for optimizer onboarding route
* feat: magic and reports fixes
* feat: regex route support, fixes
* feat: merchant la showwhen fix
* fix: partnerships fixes

---------

Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>
Co-authored-by: prem-io <prem.g@razorpay.com>
Co-authored-by: udayraj-rzp <udayraj.deshmukh@razorpay.com>

* feat: validate route util refactor
* feat: route fixes for partners dashboard
* feat: added Fix for Sidebar and Reminders
* feat: transaction revamp stable
* feat: TransactionV2 stable
* feat: UT fixes
* fix: sidebar link highlight in partner dashboard
* fix: fix splitz routes (#13360)
* feat: fix fallback
* fix: homepage rendering issue & partner dashboard tab highlight
* fix: details components fix
* fix: remove isActive from ProductWrapper
* route path fixes
* feat: updated show when route fix
* reminder settings
* fix: fix txns route location state passing
* feat: withRouter ts
* chore: prompt local alternative & Navlink/Link to prop refactor
* fix: ssab bugs
* eslint fixes
* feat: fix pricing page route navigation for desktop (#13383)
* feat: fix pricing url
* fix: partner dashboard splitz routes
* fix: merge conflicts in NestedverticalTab
* fix: test-util fix for history
* test: affordability and payments UT fixes
* ut fixes
* feat: fix some txn uts
* test: fix SettlementsBannerV2.test.js
* ut fix, product listing, gateway card
* feat: types Issues Fixes: TS version upgrade, WithRouter types, Routes Fixes
* ut: account details
* feat(imp): decoupled routeguard / showwhen from store
* chore: remove console.log from RouteGuard
* test: fix BankAccountsAndSettlements
* feat: ut fixes

---------

Co-authored-by: Joel Jaimon <joel.jaimon99@gmail.com>
Co-authored-by: prem-io <prem.g@razorpay.com>
Co-authored-by: udayraj-rzp <udayraj.deshmukh@razorpay.com>
Co-authored-by: loombarishav <rishav.loomba@razorpay.com>
Co-authored-by: AnshulJS <anshul.nautiyal@razorpay.com>
Co-authored-by: Parth sethi <parth.sethi@razorpay.com>
Co-authored-by: Shivam K S <shivam.s@razorpay.com>

* feat: ut fixes

* fix: validate workflow

* fix: erroneous imports

* fixes for merchantLA

* eslint fixes

* feat: fixes

* fix(imp): skipped 6 ut suites

* fix: index to app route changes

* eslint fixes

* fix: redirect to app only on root path

* fix: remove basename to fix signup route

* chore: clean up dead code in withRouter

* feat: setup module federation base

* fix: typescript issues (#13508)

* fix: typescript issues

* chore: update lockfile

* fix: deprecated type in ProgressSteps

* feat: setup self serve micro app base (#13562)

* fix: duplicate import issues

* feat: setup self serve micro app base

* fix: cleanup

* fix: universe build flags

* fix: review comments cleanup

* fix: self self nohoist

* fix: webpack chunk name

* feat: module federation - setup self self router (#13645)

* refactor: merge conflicts

* feat: state sync middleware (#13619)

* feat: state sync middleware

* fix: import from shell

* create zustand store as single instance

* fix: typescript issues in commonStore import

* redux store + reducers + collections setup complete

* complete payments reducer

* removed selfserve instance from shell app

* fixed microapp redux instance

* fix: typescript project include issue

* fix: web baseURL

* chore: cleanup testUtil references

* fix: remove reduandant lines and refactor code

* fix: removed div

---------

Co-authored-by: prem-io <prem.g@razorpay.com>

* revert: web tsconfig baseUrl (#13697)

* initial commit shared library (#13677)

* initial commit shared library

* Enable libs sharing

* chore: add example of shared utils

* feat: change the TS config for the monorepo

* feat(tsconfig): move paths to root ts config

* remove ts from root

* feat: transactions v2 migration to selfserve micro-app (#13719)

* feat: render micro-app below transactions v2
* chore: git mv v2 code with no changes
* chore: copy v2 back to original place
* fix: absolute paths to merchant/views
* fix: imports from Settlements
* chore: point rzp-utils imports to shared lib
* feat: setup rzp-utils from shared-ui

* fix: sourceType module issue with js files in shared-utils

* chore: git mv abExperimentsMap to shared-utils

* fix: babel import extension issue in shared-utils

* fix: currency helper import in rzp-utils

* fix: imports for currencies and third-party libs in rzp-utils

* chore: move acronyms to shared-utils

* chore: move date-utils to shared-utils

* chore: move splitz/utils to shared-utils

* chore: move analytics to shared-utils

* fix: analytics utils imports

* chore: make styled-components singleton

* fix: analytics imports

* fix: react-lottie and country codes imports

* chore: move copyToClipboard to shared-utils

* fix: navigator constants import

* fix: shared-ui setup for Seamless components in shared-utils

* feat: custom clipboard and related babel plugins

* fix: utils import in custom clipboard

* chore: move rest-fetch to shared-utils

* chore: move localStorage to shared-utils

* fix: home data import

* chore: move transactions assets to shared-ui

* chore: move modals reducers to shared-utils

* chore: move immutable to shared-utils

* chore: move settlements reducer to shared-utils

* chore: move ajax to shared-utils

* chore: move settlements models to shared-utils

* chore: move useMobile hook to shared-utils

* chore: cleanup and Blade wrapper

* feat: add session to commonStore and fix ajax util

* chore: comment out non-working parts of migration

* fix: eslint (#13680)

* fix: add unicorn package

* fix: remove unicorn plugin and resolution for typescript-eslint/eslint-plugin

* chore: move eslint config to web

move eslint config to web

* fix: web eslint issue

* fix: lint error

* lint: don't print warnings

* chore: move stylelint inside web

* fix: update yarn lock

* fix: include json in tsconfig

* fix: remove wrong react-router-dom types package

* fix: validate workflow command

* fix: error TS4082 module using private name

* fix: error TS4023 external module cannot be named

---------

Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>
Co-authored-by: dhruvdutt <dhruvdutt.jadhav@gmail.com>

* feat: migrate full self-serve code to micro-app (#13777)

* fix: assets path resolution
* revert: change in webpack assets manifest
* fix: assets path issue when importing from shared-ui
* chore: move transactions assets to micro-app
* chore: expose navigator constants from shell
* chore: enable payments tab
* chore: move ErrorBoundary to shared-ui
* chore: expose ShowWhen from shell
* chore: comment out redux provider in selfserve micro app
* chore: Replaced connect with zustand for accessing session data
* chore: move Dropdown to shared-ui
* chore: enable top overview filters
* chore: enable bottom overview
* refactor: remove RouteGuard dependency from PaymentsContainer
* feat: mfe routing with multiple provider instance (#13823)
* feat: self-serve routing with multiple instances of provider
* wrapped routes with provider instance

---------

Co-authored-by: prem-io <prem.g@razorpay.com>

* Migrate payments container (#13902)

* fix: assets path resolution

* revert: change in webpack assets manifest

* chore: enable payments tab

* chore: expose ShowWhen from shell

* chore: enable all the tabs

* feat: self-serve routing with multiple instances of provider

* chore: enable top overview filters

* chore: enable bottom overview

* resolved PR comments

* expose DownloadSwiftCopy component from shell

* exposed withRouter HOC from shell

* update ajax import to @dashboard/shared-utils

* move LazyLoader to shared-utils

* resolve MaskedContact import, refactored MaskedContact usage

* chore: move Amount to shared-ui

* fix: selfserve production build

* chore: move xss-sanitizer to shared-utils

* chore: move useViewPort to shared-ui

* chore: move useMobile to shared-ui

* chore: move Popover to shared-ui

* chore: move Tooltip to shared-ui

* chore: move debounce to shared-utils

* chore: move EntityTable to shared-ui

* chore: move Table to shared-ui

* chore: move PlaceholderLoader to shared-ui

* chore: move EntityItemRow to shared-ui

* chore: move Pager and Spinner to shared-ui

* chore: move Banner to shared-ui

* chore: move DateRangePickerField to shared-ui

* chore: move SuspenseWithLoader to shared-ui

* chore: move Loader to shared-ui

* chore: migrate CountryCodeInput to shared-ui

* chore: expose reducers/collection from shell

* chore: move ListContainer to shared-ui

* chore: move validators to shared-utils

* chore: move notifications reducer to shared-utils

* chore: move User typings to shared-utils

* feat: enable PaymentsContainer

* chore: fixed payments container fetching

* chore: removed duplicate PaymentsContainer import

---------

Co-authored-by: prem-io <prem.g@razorpay.com>

* Micro app redux connection (#13912)

* fix: assets path resolution

* revert: change in webpack assets manifest

* chore: enable payments tab

* chore: expose ShowWhen from shell

* chore: enable all the tabs

* feat: self-serve routing with multiple instances of provider

* chore: enable top overview filters

* chore: enable bottom overview

* resolved PR comments

* expose DownloadSwiftCopy component from shell

* exposed withRouter HOC from shell

* update ajax import to @dashboard/shared-utils

* move LazyLoader to shared-utils

* resolve MaskedContact import, refactored MaskedContact usage

* chore: move Amount to shared-ui

* fix: selfserve production build

* chore: move xss-sanitizer to shared-utils

* chore: move useViewPort to shared-ui

* chore: move useMobile to shared-ui

* chore: move Popover to shared-ui

* chore: move Tooltip to shared-ui

* chore: move debounce to shared-utils

* chore: move EntityTable to shared-ui

* chore: move Table to shared-ui

* chore: move PlaceholderLoader to shared-ui

* chore: move EntityItemRow to shared-ui

* chore: move Pager and Spinner to shared-ui

* chore: move Banner to shared-ui

* chore: move DateRangePickerField to shared-ui

* chore: move SuspenseWithLoader to shared-ui

* chore: move Loader to shared-ui

* chore: migrate CountryCodeInput to shared-ui

* chore: expose reducers/collection from shell

* chore: move ListContainer to shared-ui

* chore: move validators to shared-utils

* chore: move notifications reducer to shared-utils

* chore: move User typings to shared-utils

* feat: enable PaymentsContainer

* chore: fixed payments container fetching

* chore: removed duplicate PaymentsContainer import

* pass user data as props to EntityTable

* chore: Replace connect with Zustand for isWebView in CustomClipboard

* sync app reducer to zustand and resolve EntityRowItem error

* fix react-dates initialization

* chore:replace ZustandWrapper with withZustand

* chore: resolve paymentReducer import from exposed collection import

* code refactor

* chore: import analyticsTrack and getCommonSegmentProperties from shared-utils

* chore: removed .ts from webpack expose

* chore: remove stale comment

---------

Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>

* feat: add experiment for selfserve microfrontend (#13939)

* feat: add experiment for selfserve microfrontend
* feat: render microfrontend based on experiment
* fix: routing

* refactor: remove unnecessary exposes from shell (#13949)

* chore: fix type errors for common store (#13961)

* chore: fix type errors for common store

* fix: withRouter type error

* removed import user type from session.ts

* refactor: bump universe version, update jest path

---------

Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>
Co-authored-by: dhruvdutt <dhruvdutt.jadhav@gmail.com>

* web: cleanup universe utils

* feat: nx CI setup (#13774)

* feat: lint ci using nx affected

* fix: branch name

* fix: run command

* fix: branch name

* fix: fetch branch

* fix: provide base and head branch

* fix: try removing fetch master

* feat: test nx affected on CI

* fix: change branch name

* fix: fetch branch

* feat: typescript compiler ci

* ci: change base branch

* ci: update ci name

* ci: fetch master

* ci: tsc ci

* ci: try default master and head

* ci: base as master

* revert: navigator.js

* ci: build using nx affected

* fix: change target

* refactor: ci remote entry files

* refactor: add bootstrap files in all apps

* refactor: add scripts

* ci: build - selfserve devstack

* ci: temp build newauth

* fix: lint fixes for self-serve

* ci: temp build newauth

* fix: eslint issue

* ci: temp build newauth

* ci: temp build newauth

* ci: build all

* fix: change typescript

* ci: parallel build run

* fix: remove root from self-serve eslint configuration

* fix: self-serve build

* ci: remove nx build workflow

* ci: add check on web build

* self-serve: update devstack remote path

* ci: validate update

* ci: show affected issue

* ci: show affected issue

* ci: nx install issue

* refactor: update devstack paths for self serve (#13963)

* env: asset paths

* env: asset paths

* ci: update build workflow content type

* ci: add check on web

* update universe packages

---------

Co-authored-by: dhruvdutt <dhruvdutt.jadhav@gmail.com>

* Feat/module federation publish shared (#13904)

* feat: "added shared ui config fix

* fix: nx shared-ui tsc

* lint: typecheck file

* refactor: remove the published css import

* feat: universe based Eslint support

* shared utils eslint & tsc setup

* Temp -Mark paths as modules

* remove published files

* added missing import

---------

Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>

* ci: resolve eslint issues

* ci: resolve import issues

* feat: updated ENV (#14008)

Co-authored-by: loombarishav <rishav.loomba3razorpay.com>

* Fix/mfe state management - Notifications and Modal fixes (#14105)

* Moved the Modal component state to common store to make that redux agnostic and more flexible

* Basic Cleanup, Removed non required changes

* feat: added a new Federate Module (Digital Bills) to PG Dashboard

Digital Bills correspond to the Billme Partner Portal. Bringing the full suite of features from
Billme to Razorpay One Dashboard. A new MFE (Digital Bills) is added. Users can navigate to this
module by clicking on "Digital Bills" in left navbar.

* feat: graphql and Jest setup (#14195)

* feat: graphql and Jest setup

Graphql setup done, using the same instance exposed from shell app. Jest setup done for unit tests.

* chore: convert test file to typescript

* chore: renamed valid filename

* chore: code cleanup for digital bills

* chore: file, folder restructuring

* chore: removed unnecessary configs

* refactor: refactor

* refactor: refactor routeguard

* refactor: refactor

n

* feat: digital bills icon

* fix: fixed shell remote filename

* chore: removed unused dep

* refactor: minor refactors

* refactor: blade version change

---------

Co-authored-by: dhruvdutt <dhruvdutt.jadhav@gmail.com>
Co-authored-by: Abhijeet Singh <abhijeet.singh@razorpay.com>
Co-authored-by: Joel Jaimon <joel.jaimon99@gmail.com>
Co-authored-by: prem-io <prem.g@razorpay.com>
Co-authored-by: udayraj-rzp <udayraj.deshmukh@razorpay.com>
Co-authored-by: loombarishav <rishav.loomba@razorpay.com>
Co-authored-by: AnshulJS <anshul.nautiyal@razorpay.com>
Co-authored-by: Parth sethi <parth.sethi@razorpay.com>
Co-authored-by: Shivam K S <shivam.s@razorpay.com>
Co-authored-by: Prashant Chaudhary <prashant.chaudhary@razorpay.com>
Co-authored-by: Parth <71763920+parth-p-ui@users.noreply.github.com>
Co-authored-by: Rishav Loomba <87748732+loombarishav@users.noreply.github.com>