CE-4378: Implement Ability to Call Affordability Cache Invalidation API (#27976)
* Create AffordabilityService Class to Help Communicate With checkout-affordability-api Microservice

* Implement Ability to Invalidate Affordability Cache

The checkout-affordability-api cache would be invalidated for a merchant if a
new Offer (or) EMI Plan (or) Cardless EMI Provider Terminal (or) Paylater
Provider Terminal is created, updated or deleted against that merchant.

* Refactor to Have Only One AffordabilityObserver Class

* Place Affordability Service Provider in config/app.php

I've delibrately not registered the affordability service provider as it
should be enabled after the `checkout-affordability-api` service is live
on production.

* CE-4378: Modify Invalidate Cache to Point to a a New Twirp Endpoint

* CE-4378: Modify to Make a Post Request to Invalidate Affordability Cache

* CE-4378: Register AffordabilityServiceProvider as API is Live on Production

* CE-4378: Use Separate Service Secret for Communicating With Affordability GoLang API

* CE-4378: Send Merchant Keys in Post Body for InvalidateCache Request

* CE-4378: Add See to Methods Used By Handle

* CE-4378: Fix Indentation

* Fix Error "Target class [rzp.mode] does not exist"

* Fix Tests Failing Due to ArgumentError

Test were failing due to the following error:
```
TypeError: Argument 1 passed to RZP\Models\Base\AffordabilityObserver::invalidateAffordabilityCache()
must be an instance of RZP\Models\Merchant\Entity
```

This is happening because all tests create emi plans, offers & terminals before creating the actual merchant.

I've allowed invalidateAffordabilityCache() to accept & handle null in merchant param.

* CE-4378: Refactor to Use Account::TEST_ACCOUNT Instead of '10000000000000' in Tests

Co-authored-by: rzpcibot <64553331+rzpcibot@users.noreply.github.com>